<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TfsEd.Core\TfsEd.Core.csproj" />
    <ProjectReference Include="..\TfsEd.Server\TfsEd.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.12" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>tfsed</AssemblyName>
    <RootNamespace>TfsEd.Cli</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TfsEd.Tests" />
  </ItemGroup>

</Project>
